### 检查手机号是否存在
POST {{host}}/v1/auth/signup/phone/exist
Content-Type: application/json

{
  "phone": "{{phone}}"
}

### 检查邮箱是否注册
POST {{host}}/v1/auth/signup/email/exist
Content-Type: application/json

{
    "email": "jobs@qq.com"
}

### 获取图形验证码
POST {{host}}/v1/auth/verify-codes/captcha
Content-Type: application/json

### 发送短信验证码
POST {{host}}/v1/auth/verify-codes/phone
Content-Type: application/json

{
  "phone":"{{phone}}",
  "captcha_id": "hqv3R9TD687RvJyXqho7",
  "captcha_answer": "001295"
}

### 给邮箱发送验证码
POST {{host}}/v1/auth/verify-codes/email
Content-Type: application/json

{
  "email":"{{email}}",
  "captcha_id": "captcha_skip_test",
  "captcha_answer": "458430"
}

### 使用手机号注册账号
POST {{host}}/v1/auth/signup/using-phone
Content-Type: application/json

{
    "name":"mercury",
    "password":"secret",
    "password_confirm":"secret",
    "verify_code": "123456",
    "phone": "{{phone}}"
}

### 使用email注册账号
POST {{host}}/v1/auth/signup/using-email
Content-Type: application/json

{
  "name":"mercuryemail",
  "password":"secret",
  "password_confirm":"secret",
  "verify_code": "123123",
  "email": "{{email}}"
}

### 使用手机号登录
POST {{host}}/v1/auth/login/using-phone
Content-Type: application/json

{
  "phone":"{{phone}}",
  "verify_code":"123456"
}

### 使用账号密码登录
POST {{host}}/v1/auth/login/using-password
Content-Type: application/json

{
    "login_id":"{{email}}",
    "password":"secret",
    "captcha_id": "captcha_skip_test",
    "captcha_answer": "458430"
}

### 刷新jwt
POST {{host}}/v1/auth/login/refresh-token
Content-Type: application/json
Authorization: Bearer {{access_token}}

### 通过手机找回密码
POST {{host}}/v1/auth/password-reset/using-phone
Content-Type: application/json

{
  "phone": "{{phone}}",
  "verify_code": "123456",
  "password": "111111"
}

### 通过邮箱找回密码
POST {{host}}/v1/auth/password-reset/using-email
Content-Type: application/json

{
  "email": "{{email}}",
  "verify_code": "123456",
  "password": "111111"
}

### 获取当前登录用户信息
GET {{host}}/v1/user
Content-Type: application/json
Authorization: Bearer {{access_token}}

### 获取所有用户信息

GET {{host}}/v1/users?page=1&order=desc
Content-Type: application/json

### 新建分类
POST {{host}}/v1/categories/store
Content-Type: application/json
Authorization: Bearer {{access_token}}

{
  "name": "新建分类",
  "description": "这里是描述"
}

### 更新分类
PUT {{host}}/v1/categories/update/1
Content-Type: application/json
Authorization: Bearer {{access_token}}

{
  "name": "新分类名称",
  "description": "这里是描述"
}

### 获取所有分类
GET {{host}}/v1/categories
Content-Type: application/json
Authorization: Bearer {{access_token}}

### 删除分类
DELETE {{host}}/v1/categories/delete/11
Content-Type: application/json
Authorization: Bearer {{access_token}}

### 创建话题
POST {{host}}/v1/topics
Content-Type: application/json
Authorization: Bearer {{access_token}}

{
  "title": "我发的帖子",
  "body": "这里是帖子描述这里是帖子描述",
  "category_id": "2"
}

### 更新话题
PUT {{host}}/v1/topics/1
Content-Type: application/json
Authorization: Bearer {{access_token}}

{
  "title": "修改后的帖子标题",
  "body": "这里是帖子描述这里是帖子描述",
  "category_id": "3"
}
